### ISSUE TITLE
Please don’t load 120MB of GIFs in the readme

### ISSUE THREAD

**Issue by chris-morgan** [ForeignGods/Sorting-Algorithms-Blender#3]
Loading the front page of this repository causes the download of 120MB of GIFs.

Please don’t do this. Please use a proper video codec instead, which will allow the downloads to only be done on request, be much smaller, and get proper scrubbing controls and such.

Also, the biggest one (bubble_circle.gif, 28MB) is stored in the repository. As a general rule, you shouldn’t store large build artefacts like that in the repository, it just bloats the repository and makes working with it slow.

**Comment by blackspike** [comment]
Here you go, I've converted them to mp4 for you!

[videos.zip](https://github.com/ForeignGods/Sorting-Algorithms-Blender/files/8998894/videos.zip)
```
 41K 28 Jun 08:58 174031317-2c261df1-6786-42e5-be08-1a7f5fccbca6.mp4
147K 28 Jun 08:58 174032376-9b9768aa-5891-468e-a7a9-1d494374c5a4.mp4
 86K 28 Jun 08:58 174032744-6d968c18-8fdb-4268-937f-55e910f8c4d5.mp4
 36K 28 Jun 08:58 174033035-b6b9527a-3d12-4844-b066-50b4cb9d11ef.mp4
310K 28 Jun 08:58 174035509-714265d2-4d27-4d77-b809-997f4e233feb.mp4
 46K 28 Jun 08:58 174035707-e1475bd4-a3c6-4e74-ba9f-30b57335adfe.mp4
268K 28 Jun 08:58 174149862-2ed3c492-0987-4194-834f-fc5276299bcc.mp4
1.8M 28 Jun 08:58 174154736-ada0e27f-88d0-4707-ba99-14ed967cce21.mp4
182K 28 Jun 08:58 174156159-605f5121-06c3-4314-a22c-5f7919bb9c44.mp4
591K 28 Jun 08:58 174157836-a4571ad7-0fd1-4237-9fb2-dc2d730a64c7.mp4
618K 28 Jun 08:58 174161064-3fff2b70-90db-425c-acab-0d87040ec205.mp4
283K 28 Jun 08:58 174161905-a3a2d1bd-0064-4e23-92b3-50da150c6f0c.mp4
133K 28 Jun 08:58 174625884-ed64292c-c5cf-4fe8-af9f-bddb2e5fa6bf.mp4
871K 28 Jun 08:58 175014980-af6f702b-7206-4bf4-9d00-0a7f7fc5d15d.mp4
2.3M 28 Jun 08:58 175064056-5a766e7b-2804-4ed6-b05d-786d26ebcbfb.mp4
5.8M 28 Jun 08:58 bubble_circle.mp4
```

**Comment by ForeignGods** [comment]
You're right, thank you for making me aware of this.
I will replace them.
The videos in the .zip file look a bit blurry.
I'll render everything in blender, but thanks anyway.

**Comment by ForeignGods** [comment]
As I started replacing the GIFs with .mp4 files, I noticed that the video player looks like the one seen below.
In my opinion, this takes away from the aesthetic I want for the page.
In addition, I really like that the GIFs autoplay and loop infinitely.
Can you elaborate on why it's bad that 120mb are downloaded when loading the page?
But I will definitely remove the GIF (bubble_circle.gif) that's stored in the repository.

https://user-images.githubusercontent.com/78089013/176217715-58db65fd-3eae-4b9c-a4b6-e4981b3ffece.mp4

**Comment by chris-morgan** [comment]
Yeah, it’s a real video player. *That’s the point.* It lets the user control it properly, pause button, scrub bar and all. Not autoplaying is a *feature*. Not looping is a minor loss only. (Looks like GitHub ignores a `loop` attribute if you use `<video>` syntax.)

As for why 120MB of auto-loading images is bad: it extremely significantly breaks expectations on how much data loading a page will use (I’d expect less than 2MB for such a page, typically far less), and *data costs money*. I personally have been in situations where it would have concretely cost me $10 to load the page several times in the past few years, and higher (sometimes drastically higher) is not uncommon for others, or perhaps you may just make it so that they lose internet access for the rest of the month.

Concerning bubble_circle.gif, to truly remove it from the repository you’ll need to use git-filter-branch and force push. (Refer to the example shown in `git filter-branch --help`.)

**Comment by blackspike** [comment]
you'll want to add  `playsinline loop autoplay muted`  to your attributes, e.g. `<video playsinline loop autoplay muted src="/video.mp4">` – these will ensure the player will hide the controls

**Comment by ForeignGods** [comment]
I've reduced the size of all the GIFs, the page now loads approx. 20mb in total.
Compared to other pages on GitHub containing GIFs this seems to be a reasonable size.

I also removed bubble_circle.gif with git-filter-branch and force push.
But now all the repositories that have been forked before the deletion of bubble_circle.gif are approx. "70 commits ahead and 75 commits behind".
As I understand the git-filter-branch command erases the entire history of the removed file, but can you explain why the forks are behind and ahead at the same time?

**Comment by kiicia** [comment]
because changing history changes each commit's hash
